export { default as BessSolar } from './bess-solar.png'
export { default as JWControl } from './jw-control.png'
export { default as RxTeeth } from './rxteeth.png'
export { default as SkyTech } from './skytech.png'
export { default as SmartTransit } from './smart-transit.png'
export { default as Surichakra } from './Surichakra.png'
export { default as GaloissAcademy } from './qr-assistance.png'
export { default as BelcorpMvp } from './belcorp.png'
