export { default as Figma } from './figma.svg?react'
export { default as Github } from './github.svg?react'
export { default as Linkedin } from './linkedin.svg?react'
export { default as Mail } from './mail.svg?react'
export { default as ChevronRight } from './chevron-right.svg?react'
